spring.application.name=IndiChessBackend

spring.datasource.url=jdbc:mysql://localhost:3306/chess
spring.datasource.username=root
spring.datasource.password=2004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.oauth2.client.registration.google.client-id=1071899417516-20gqe89fcrgddmp6ip1stnc148ea6fg4.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email





